name: tijuca
description: "A fast, abstract, and highly testable key-value local database wrapper for Dart and Flutter."
version: 1.0.0
homepage:

environment:
  sdk: ^3.13.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mmkv: "^2.4.2"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
